import {
  BattleContestant,
  CharacterArchetype,
  CharacterScenario,
  CharacterTrait,
  DreamWish,
  FavoriteCategory,
  JourneyStation,
  PersonOption,
  QualityOption,
} from './types';

// Basic partner settings
export const PARTNER_FIRST_NAME = "E'zoza";
export const PARTNER_LAST_NAME = 'Islomova';
export const CORRECT_LAST_NAME = 'islomova';
export const MY_NAME = 'Men';

// Intro
export const INTRO_MESSAGES = [
  { text: "Salom, E'zozam...", delay: 600, emoji: '💖' },
  { text: 'Bu kecha siz uchun maxsus', delay: 2200, emoji: '✨' },
  { text: "Tayyor bo'lsangiz, sarguzashtni boshlaylik", delay: 4200, emoji: '🌙' },
];

// Optional legacy game constants (kept for compatibility)
export const QUALITIES: QualityOption[] = [
  { id: '1', text: 'Chiroyli', emoji: '🌸', isGood: true },
  { id: '2', text: 'Mehribon', emoji: '🤍', isGood: true },
  { id: '3', text: 'Aqlli', emoji: '🧠', isGood: true },
  { id: '4', text: 'Quvnoq', emoji: '😄', isGood: true },
  { id: '5', text: 'Jozibali', emoji: '✨', isGood: true },
];

export const PEOPLE: PersonOption[] = [
  { id: 'p1', name: 'Tasodifiy mushuk', emoji: '🐱', description: 'Chiroyli, lekin mushuk...', isCorrect: false },
  { id: 'p2', name: 'Elon Musk', emoji: '🚀', description: 'Boy, lekin siz emas', isCorrect: false },
  { id: 'p3', name: "E'zoza Islomova", emoji: '👑', description: "Dunyodagi eng go'zal inson", isCorrect: true },
  { id: 'p4', name: 'BTS', emoji: '🎤', description: 'Mashhur, lekin...', isCorrect: false },
  { id: 'p5', name: 'Spider-Man', emoji: '🕷️', description: "Qahramon, lekin siz emas", isCorrect: false },
  { id: 'p6', name: 'Dori Beruvchi Xola', emoji: '💊', description: 'Mehribon, lekin...', isCorrect: false },
];

export const NO_BUTTON_PHRASES = [
  "Yo'q",
  'Ishonchingiz komilmi?',
  'Aniqmi?',
  "Yana bir o'ylab ko'ring!",
  'Songgi imkoniyat!',
  'Nahotki?',
  "Pushaymon bo'lishingiz mumkin!",
  "Yana bir bor o'ylab ko'ring!",
  'Mutlaqo ishonchingiz komilmi?',
  "Bu xato bo'lishi mumkin!",
  'Rahmingiz kelsin!',
  "Bunchalik sovuqqon bo'lmang!",
  "Fikringiz o'zgardimi?",
  "Qayta o'ylab ko'rmaysizmi?",
  "Bu so'nggi javobingizmi?",
  'Yuragimni sindiryapsiz ;(',
  "Men yig'lab yuboraman!",
  'Iltimos...',
];

export const SUCCESS_LETTER = {
  greeting: "Aziz E'zozam,",
  paragraphs: [
    'Ha deyishingizni bilardim! Lekin buni eshitish baribir yuragimni tez urdiryapti.',
    "Siz mening hayotimdagi eng go'zal insonsiz. Sizning tabassumingiz va mehribonligingiz menga juda qadrli.",
    "Bu kichik o'yinda qatnashganingiz uchun rahmat. Bu shunchaki o'yin emas, yurakdan yozilgan hislar.",
    'Siz bilan har bir kun bayram, har bir lahza sovga.',
  ],
  closing: 'Abadiy sizniki,',
  signature: 'Sizni sevuvchi inson',
};

export const CONFETTI_COLORS = [
  '#ec4899',
  '#f43f5e',
  '#f97316',
  '#eab308',
  '#22c55e',
  '#3b82f6',
  '#8b5cf6',
  '#f472b6',
  '#fb923c',
  '#facc15',
  '#a78bfa',
  '#34d399',
];

export const HEART_EMOJIS = ['💖', '💗', '💓', '💞', '💕', '💘', '🌸', '✨', '💫', '🤍'];

// Name game
export const FAKE_FIRST_NAMES = [
  'Nodira',
  'Malika',
  'Dilnoza',
  'Zulfiya',
  'Gulnora',
  'Shahlo',
  'Madina',
  'Barno',
  'Kamola',
  'Nilufar',
  'Sevinch',
  'Dildora',
  'Mohira',
  'Lobar',
  'Nafisa',
  'Zarina',
];

export const FAKE_LAST_NAMES = [
  'Karimova',
  'Xudoyberdiyeva',
  'Nurmatova',
  'Umarova',
  'Toshpulatova',
  'Abdullayeva',
  'Rahimova',
  'Mirzayeva',
  'Yusupova',
  'Nazarova',
  'Ergasheva',
  'Qodirova',
  'Saidova',
  'Hakimova',
  'Rustamova',
];

export const WRONG_NAME_PHRASES = [
  'Akula bu ismni yoqtirmadi va haydab yubordi!',
  "Bu ismli qizlar bu yurakka sig'maydi!",
  "Akula g'azablandi, bu ism emas!",
  'Dengiz bu ismni qaytarib yubordi!',
  "Bu marvarid soxta, akula uni yeb qo'ydi!",
  "Akula: 'Bu ism kemaga yaramaydi!'",
  'Yurak boshqa ismni kutyapti...',
  "Bu ism to'lqinlar bilan ketdi!",
  "Noto'g'ri! Akula g'azablanmoqda!",
  'Akula bu marvaridni parchalab tashladi!',
];

export const WRONG_SURNAME_PHRASES = [
  'Bu familiya dengiz tubida qolsin!',
  'Akula bu familiyani haydab yubordi!',
  'Bu familiya bizning kemaga yaramaydi!',
  "Akula: 'Boshqa familiya kerak!'",
  'Yurak bu familiyani tanlamaydi!',
  'Akula to`lqinlar bilan bu familiyani olib ketdi!',
  'Yana urinib koring, akula kutyapti!',
  'Bu marvarid soxta, akula hujum qildi!',
  "Akula g'azablandi, bu familiya emas!",
  'Noto`g`ri familiya! Akula parchaladi!',
];

// Character game
export const CHARACTER_TRAITS: Record<CharacterTrait, { name: string; emoji: string }> = {
  romantik: { name: 'Romantik', emoji: '💞' },
  mehribon: { name: 'Mehribon', emoji: '🤍' },
  sarguzashtsevar: { name: 'Sarguzashtsevar', emoji: '🧭' },
  ijodkor: { name: 'Ijodkor', emoji: '🎨' },
  aqlli: { name: 'Aqlli', emoji: '🧠' },
  kuchli: { name: 'Kuchli', emoji: '🔥' },
  quvnoq: { name: 'Quvnoq', emoji: '😄' },
};

export const CHARACTER_SCENARIOS: CharacterScenario[] = [
  {
    id: 'inner_world',
    question: "Kozingizni yumib, ichki olamingizni qanday tasavvur qilasiz?",
    emoji: '🪞',
    cardBack: '🃏',
    diaryPlaceholder: 'Ichki olamingizdagi eng qimmatli narsa haqida yozing...',
    choices: [
      { id: 'i1', text: "Rangli hayollar va ijodga to'la dunyo", emoji: '🎨', trait: 'ijodkor' },
      { id: 'i2', text: "Issiq, mehrli va tinch dunyo", emoji: '🤍', trait: 'mehribon' },
      { id: 'i3', text: 'Kashfiyot va sayohatlarga boy dunyo', emoji: '🌍', trait: 'sarguzashtsevar' },
    ],
  },
  {
    id: 'love_language',
    question: 'Sevgini asosan qanday ifodalay olasiz?',
    emoji: '💌',
    cardBack: '🃏',
    diaryPlaceholder: 'Sevgini qanday his qilasiz va ifodalay olasiz...',
    choices: [
      { id: 'l1', text: "Nozik sozlar, xatlar va hisli gaplar", emoji: '✍️', trait: 'romantik' },
      { id: 'l2', text: "Gamxorlik va amaliy yordam bilan", emoji: '🤲', trait: 'mehribon' },
      { id: 'l3', text: 'Birga sarguzasht qilish orqali', emoji: '🧭', trait: 'sarguzashtsevar' },
    ],
  },
  {
    id: 'strength',
    question: 'Qiyin paytda sizga eng katta kuch nima beradi?',
    emoji: '💪',
    cardBack: '🃏',
    diaryPlaceholder: 'Sizni kuchlantirgan bir vaziyatni eslang...',
    choices: [
      { id: 's1', text: 'Ichki ishonch va qat`iyat', emoji: '🔥', trait: 'kuchli' },
      { id: 's2', text: "Yaqinlarimning sevgisi va yordami", emoji: '🤍', trait: 'mehribon' },
      { id: 's3', text: "Sovuq bosh bilan to'gri qaror topish", emoji: '🧠', trait: 'aqlli' },
    ],
  },
  {
    id: 'dreams',
    question: 'Tungi osmon ostida ko`proq nimalarni o`ylaysiz?',
    emoji: '🌌',
    cardBack: '🃏',
    diaryPlaceholder: 'Eng chuqur orzuingiz haqida yozing...',
    choices: [
      { id: 'd1', text: 'Sevgi va qalbdagi iliq tuygular', emoji: '💖', trait: 'romantik' },
      { id: 'd2', text: 'Kelajakdagi katta maqsadlar', emoji: '🎯', trait: 'kuchli' },
      { id: 'd3', text: 'Dunyoni ko`rish va kashf qilish', emoji: '✈️', trait: 'sarguzashtsevar' },
    ],
  },
  {
    id: 'empathy',
    question: "Yaqin odamingiz xafa bo'lsa, odatda nima qilasiz?",
    emoji: '🫂',
    cardBack: '🃏',
    diaryPlaceholder: 'Boshqalar uchun his qiladigan tuygularingizni yozing...',
    choices: [
      { id: 'e1', text: 'Quchoqlab, hislarni baham koraman', emoji: '💞', trait: 'romantik' },
      { id: 'e2', text: 'Yechem topishga yordam beraman', emoji: '🧠', trait: 'aqlli' },
      { id: 'e3', text: 'Kayfiyatini kulgu bilan kotaraman', emoji: '😄', trait: 'quvnoq' },
    ],
  },
  {
    id: 'freedom',
    question: 'Faqat ozingiz qolganda nima bilan band bolasiz?',
    emoji: '🕊️',
    cardBack: '🃏',
    diaryPlaceholder: 'Hech kim bilmaydigan odatingizni yozing...',
    choices: [
      { id: 'f1', text: 'Musiqa qoyib raqsga tushaman', emoji: '💃', trait: 'quvnoq' },
      { id: 'f2', text: 'Yozaman, chizaman yoki yarataman', emoji: '🎨', trait: 'ijodkor' },
      { id: 'f3', text: 'Oylayman va kitob oqiyman', emoji: '📚', trait: 'aqlli' },
    ],
  },
  {
    id: 'essence',
    question: 'Oz mohiyatingizni bir soz bilan ifodalang.',
    emoji: '✨',
    cardBack: '🃏',
    diaryPlaceholder: 'Ozingizni bir jumla bilan tariflang...',
    choices: [
      { id: 'w1', text: 'Sevgi', emoji: '💗', trait: 'romantik' },
      { id: 'w2', text: 'Erkinlik', emoji: '🔥', trait: 'kuchli' },
      { id: 'w3', text: 'Rang va ilhom', emoji: '🌈', trait: 'ijodkor' },
    ],
  },
];

export const CHARACTER_ARCHETYPES: CharacterArchetype[] = [
  {
    id: 'gul',
    name: 'Gul Malikasi',
    emoji: '🌹',
    traits: ['romantik', 'mehribon'],
    description: "Siz sevgi va mehrga boy insonsiz. Yaqinlaringizga iliqlik ulashasiz.",
    color: '#ec4899',
  },
  {
    id: 'oy',
    name: 'Oy Parisi',
    emoji: '🌙',
    traits: ['aqlli', 'ijodkor'],
    description: "Siz chuqur fikrli va ijodkor insonsiz. Sirli, ammo juda nafis energiyaga egasiz.",
    color: '#8b5cf6',
  },
  {
    id: 'quyosh',
    name: 'Quyosh Shahzodasi',
    emoji: '☀️',
    traits: ['quvnoq', 'mehribon'],
    description: "Siz tabassumingiz bilan atrofni yoritadigan, quvnoq va mehrli insonsiz.",
    color: '#f59e0b',
  },
  {
    id: 'olmos',
    name: 'Olmos Malikasi',
    emoji: '💎',
    traits: ['kuchli', 'aqlli'],
    description: "Siz qat`iyatli va dono insonsiz, qiyinchiliklarda ham yonalmaysiz.",
    color: '#06b6d4',
  },
  {
    id: 'yulduz',
    name: 'Yulduz Sayohatchisi',
    emoji: '⭐',
    traits: ['sarguzashtsevar', 'quvnoq'],
    description: "Siz hayotni sevuvchi va yangilikka ochiq insonsiz.",
    color: '#f97316',
  },
  {
    id: 'kamalak',
    name: 'Kamalak Parisi',
    emoji: '🌈',
    traits: ['ijodkor', 'quvnoq'],
    description: "Siz rang-barang fikrli, ijodkor va ilhom tarqatuvchi insonsiz.",
    color: '#10b981',
  },
  {
    id: 'olov',
    name: 'Olov Malikasi',
    emoji: '🔥',
    traits: ['kuchli', 'sarguzashtsevar'],
    description: "Siz jasur va oldinga intiluvchi kuchli insonsiz.",
    color: '#ef4444',
  },
];

// Favorites game
export const FAVORITE_CATEGORIES: FavoriteCategory[] = [
  { id: 'drink', name: 'Ichimlik', emoji: '🥤', question: 'Qanday ichimlik yoqtirasiz?', shelfColor: '#92400e' },
  { id: 'sweet', name: 'Shirinlik', emoji: '🍰', question: 'Eng sevimli shirinligingiz?', shelfColor: '#9d174d' },
  { id: 'fruit', name: 'Meva', emoji: '🍓', question: 'Eng yoqtirgan mevangiz?', shelfColor: '#dc2626' },
  { id: 'food', name: 'Taom', emoji: '🍝', question: 'Eng sevimli taomingiz?', shelfColor: '#ea580c' },
  { id: 'animal', name: 'Hayvon', emoji: '🐱', question: "Qanday hayvonni yaxshi ko'rasiz?", shelfColor: '#ca8a04' },
  { id: 'car', name: 'Avtomobil', emoji: '🚗', question: 'Orzudagi avtomobilingiz?', shelfColor: '#2563eb' },
  { id: 'flower', name: 'Gul', emoji: '🌷', question: 'Eng sevimli gulingiz?', shelfColor: '#ec4899' },
  { id: 'color', name: 'Rang', emoji: '🎨', question: 'Eng sevimli rangingiz?', shelfColor: '#7c3aed' },
  { id: 'music', name: 'Musiqa', emoji: '🎵', question: 'Qanday musiqa eshitishni yoqtirasiz?', shelfColor: '#0891b2' },
  { id: 'fashion', name: 'Kiyim uslubi', emoji: '👗', question: 'Eng sevimli kiyim uslubingiz?', shelfColor: '#be185d' },
  { id: 'movie', name: 'Film/Serial', emoji: '🎬', question: 'Eng sevimli film yoki serial?', shelfColor: '#4338ca' },
  { id: 'book', name: 'Kitob', emoji: '📚', question: "Qanday kitoblarni o'qiysiz?", shelfColor: '#0d9488' },
];

// Dreams game
export const DREAM_WISHES: DreamWish[] = [
  { id: 'love', title: 'Sevgi orzusi', emoji: '💖', prompt: "Sevgi haqidagi eng go'zal orzuyingiz...", starColor: '#f472b6' },
  { id: 'travel', title: 'Sayohat orzusi', emoji: '✈️', prompt: 'Qayerga sayohat qilmoqchisiz?', starColor: '#60a5fa' },
  { id: 'family', title: 'Oila orzusi', emoji: '🏡', prompt: 'Oila haqidagi eng issiq orzuyingiz...', starColor: '#fbbf24' },
  { id: 'career', title: 'Kelajak kasbi', emoji: '💼', prompt: "Kelajakda kim bo'lmoqchisiz?", starColor: '#a78bfa' },
  { id: 'happiness', title: 'Baxt tilagi', emoji: '🌈', prompt: 'Sizni eng baxtli qiladigan narsa nima?', starColor: '#34d399' },
  { id: 'destiny', title: 'Taqdir', emoji: '✨', prompt: "Taqdiringiz haqida nima deb o'ylaysiz?", starColor: '#c084fc' },
  { id: 'unique', title: 'Oziga xos orzu', emoji: '🦋', prompt: 'Faqat sizga xos eng qimmatli orzu...', starColor: '#fcd34d' },
];

// Journey scenes
export const JOURNEY_STATIONS: JourneyStation[] = [
  {
    id: 'korea',
    title: 'Koreya - Sevgi Bahori',
    subtitle: 'Birinchi bekat',
    description: "Seul kochalarida qol ushlashib yuramiz, sakura gullari ostida har lahzadan zavq olamiz.",
    emoji: '🌸',
    gradientFrom: '#fce4ec',
    gradientVia: '#f8bbd0',
    gradientTo: '#e1bee7',
    svgType: 'korea',
  },
  {
    id: 'turkey',
    title: 'Turkiya - Oltin Quyosh',
    subtitle: 'Ikkinchi bekat',
    description: "Turkiya sohilida quyosh botishini tomosha qilamiz, iliq shamolda vaqt toxtab qolgandek bo'ladi.",
    emoji: '🌅',
    gradientFrom: '#fff3e0',
    gradientVia: '#ffe0b2',
    gradientTo: '#ffcc80',
    svgType: 'turkey',
  },
  {
    id: 'maldives',
    title: 'Maldiv - Moviy Jannat',
    subtitle: 'Uchinchi bekat',
    description: "Okean ustida tongni kutib olamiz, sukunat va go'zallik ichida ikki yurak yaqinlashadi.",
    emoji: '🏝️',
    gradientFrom: '#e0f7fa',
    gradientVia: '#b2ebf2',
    gradientTo: '#80deea',
    svgType: 'maldives',
  },
  {
    id: 'paris',
    title: 'Parij - Sevgilar Shahri',
    subtitle: "To'rtinchi bekat",
    description: "Eyfel nurlari ostida raqs tushamiz va muhabbatimizni yulduzlarga aytamiz.",
    emoji: '🗼',
    gradientFrom: '#ede7f6',
    gradientVia: '#d1c4e9',
    gradientTo: '#1a1a2e',
    svgType: 'paris',
  },
  {
    id: 'home',
    title: 'Baxtli Oilamiz',
    subtitle: 'Beshinchi bekat',
    description: "Oz uyimizda iliq oila quramiz, har tong tabassum bilan boshlanadi.",
    emoji: '🏡',
    gradientFrom: '#e8f5e9',
    gradientVia: '#c8e6c9',
    gradientTo: '#a5d6a7',
    svgType: 'home',
  },
  {
    id: 'forever',
    title: 'Abadiy birga',
    subtitle: 'Oxirgi bekat',
    description: "Qol-qolga, yurak-yurakka, hayot boyi birga bolamiz.",
    emoji: '💞',
    gradientFrom: '#fce4ec',
    gradientVia: '#f8bbd0',
    gradientTo: '#fff8e1',
    svgType: 'forever',
  },
];

// ============================================================
// Final battle contestants (beauty + popularity ranking)
// ============================================================
export const BATTLE_CONTESTANTS: BattleContestant[] = [
  {
    id: 'selena_gomez',
    name: 'Selena Gomez',
    group: 'singer',
    imageNumber: 1,
    beautyScore: 90,
    popularityScore: 96,
    characterTypes: ['samimiy', 'hissiyotli', 'ijodkor'],
    strengths: ['sahnada tajribali', 'global auditoriya', 'brend tasiri'],
    charms: ['yumshoq ovoz', 'tabiiy tabassum', 'minimal uslub'],
  },
  {
    id: 'ariana_grande',
    name: 'Ariana Grande',
    group: 'singer',
    imageNumber: 2,
    beautyScore: 88,
    popularityScore: 95,
    characterTypes: ['energetik', 'perfeksionist', 'jasur'],
    strengths: ['kuchli vokal diapazoni', 'xoreografik chiqishlar', 'trend yaratuvchi'],
    charms: ['baland notalar', 'nozik qiyofa', 'sahnadagi magnetizm'],
  },
  {
    id: 'taylor_swift',
    name: 'Taylor Swift',
    group: 'singer',
    imageNumber: 3,
    beautyScore: 89,
    popularityScore: 99,
    characterTypes: ['hikoyachi', 'lider', 'mehnatkash'],
    strengths: ['songwriting mahorati', 'katta fandom', 'live show tajribasi'],
    charms: ['nozik mimika', 'elegant aura', 'samimiy aloqa'],
  },
  {
    id: 'zendaya',
    name: 'Zendaya',
    group: 'actress',
    imageNumber: 4,
    beautyScore: 90,
    popularityScore: 93,
    characterTypes: ['aqlli', 'zamonaviy', 'intizomli'],
    strengths: ['aktyorlik diapazoni', 'fashion ikona', 'media boshqaruvi'],
    charms: ['nazar tortuvchi nigoh', 'balansli uslub', 'kamerada ishonch'],
  },
  {
    id: 'jisoo',
    name: 'Jisoo',
    group: 'singer',
    imageNumber: 5,
    beautyScore: 93,
    popularityScore: 91,
    characterTypes: ['sokin', 'nazokatli', 'irodali'],
    strengths: ['global idol tajribasi', 'brend elchisi', 'kop tilli auditoriya'],
    charms: ['klassik gozallik', 'muloyim tabassum', 'premium aura'],
  },
  {
    id: 'jennie',
    name: 'Jennie',
    group: 'singer',
    imageNumber: 6,
    beautyScore: 92,
    popularityScore: 91,
    characterTypes: ['mustaqil', 'dadil', 'zamonaviy'],
    strengths: ['trend yetakchisi', 'rap-vokal moslashuv', 'sahna dominantligi'],
    charms: ['cat-eye qarash', 'fashion quvvati', 'oziga xos energiya'],
  },
  {
    id: 'dua_lipa',
    name: 'Dua Lipa',
    group: 'singer',
    imageNumber: 7,
    beautyScore: 90,
    popularityScore: 90,
    characterTypes: ['dadil', 'ritmik', 'erkin'],
    strengths: ['hitmaker', 'kuchli stage control', 'xalqaro hamkorliklar'],
    charms: ['tembrli ovoz', 'zamonaviy imidj', 'energetik vibe'],
  },
  {
    id: 'scarlett_johansson',
    name: 'Scarlett Johansson',
    group: 'actress',
    imageNumber: 8,
    beautyScore: 91,
    popularityScore: 92,
    characterTypes: ['isbotlangan', 'qatiyatli', 'jiddiy'],
    strengths: ['kop janrli rollar', 'blokbaster tajribasi', 'stabil mashhurlik'],
    charms: ['klassik hollywood ruhi', 'chuqur qarash', 'ishonchli xarizma'],
  },
  {
    id: 'emma_watson',
    name: 'Emma Watson',
    group: 'actress',
    imageNumber: 9,
    beautyScore: 90,
    popularityScore: 90,
    characterTypes: ['intellektual', 'mulohazali', 'madaniyatli'],
    strengths: ['global franchise tajribasi', 'talimiy imidj', 'nutq mahorati'],
    charms: ['sodda nafislik', 'aqlli tabassum', 'yumshoq ohang'],
  },
  {
    id: 'gal_gadot',
    name: 'Gal Gadot',
    group: 'actress',
    imageNumber: 10,
    beautyScore: 91,
    popularityScore: 89,
    characterTypes: ['jasur', 'sportiv', 'lider'],
    strengths: ['aksion rollar', 'xalqaro tanilish', 'kuchli ekran prezens'],
    charms: ['qirollik qiyofasi', 'baland ishonch', 'charismatic smile'],
  },
  {
    id: 'margot_robbie',
    name: 'Margot Robbie',
    group: 'actress',
    imageNumber: 11,
    beautyScore: 91,
    popularityScore: 90,
    characterTypes: ['moslashuvchan', 'quvnoq', 'professional'],
    strengths: ['turli rollar', 'produserlik tajribasi', 'sahna transformatsiyasi'],
    charms: ['yorqin tabassum', 'jonli mimika', 'kamera bilan oyin'],
  },
  {
    id: 'ana_de_armas',
    name: 'Ana de Armas',
    group: 'actress',
    imageNumber: 12,
    beautyScore: 92,
    popularityScore: 86,
    characterTypes: ['nazokatli', 'sirli', 'vazmin'],
    strengths: ['dramatik rollar', 'tez kotarilgan reyting', 'xalqaro loyihalar'],
    charms: ['ifodali kozlar', 'yumshoq aura', 'elegant harakat'],
  },
  {
    id: 'monica_bellucci',
    name: 'Monica Bellucci',
    group: 'actress',
    imageNumber: 13,
    beautyScore: 95,
    popularityScore: 85,
    characterTypes: ['klassik', 'oziga ishongan', 'muloyim'],
    strengths: ['afsonaviy status', 'evropa kino tajribasi', 'tabiiy ekran quvvati'],
    charms: ['timeless gozallik', 'chuqur nigoh', 'pastel nafislik'],
  },
  {
    id: 'angelina_jolie',
    name: 'Angelina Jolie',
    group: 'actress',
    imageNumber: 14,
    beautyScore: 94,
    popularityScore: 91,
    characterTypes: ['jasur', 'insonparvar', 'kuchli'],
    strengths: ['global tasir', 'katta filmografiya', 'liderlik obrazi'],
    charms: ['keskin yuz chizigi', 'dramatik aura', 'magnetik korinish'],
  },
  {
    id: 'princess_diana',
    name: 'Princess Diana',
    group: 'icon',
    imageNumber: 15,
    beautyScore: 92,
    popularityScore: 97,
    characterTypes: ['mehribon', 'nobl', 'samimiy'],
    strengths: ['xalq qalbidan joy olgan', 'tarixiy tasir', 'xayriya merosi'],
    charms: ['qirollik nazokati', 'iliq tabassum', 'sof qiyofa'],
  },
  {
    id: 'aurora',
    name: 'Aurora',
    group: 'cartoon',
    imageNumber: 16,
    beautyScore: 88,
    popularityScore: 87,
    characterTypes: ['orzuparast', 'romantik', 'muloyim'],
    strengths: ['ertak ramzi', 'klassik disney merosi', 'yumshoq obraz'],
    charms: ['oltin soch', 'malika nazokati', 'orzuvchan nigoh'],
  },
  {
    id: 'snow_white',
    name: 'Snow White',
    group: 'cartoon',
    imageNumber: 17,
    beautyScore: 87,
    popularityScore: 88,
    characterTypes: ['sodda', 'mehribon', 'pokiza'],
    strengths: ['birinchi disney ikonasi', 'bolalik nostalgiyasi', 'dostona obraz'],
    charms: ['oqila tabassum', 'klassik libos', 'yumshoq ovoz'],
  },
  {
    id: 'belle',
    name: 'Belle',
    group: 'cartoon',
    imageNumber: 18,
    beautyScore: 89,
    popularityScore: 89,
    characterTypes: ['kitobsevar', 'aqlli', 'mustaqil'],
    strengths: ['aqlli qahramon modeli', 'hikoya markazi', 'madaniy mashhurlik'],
    charms: ['jigarrang kozlar', 'sariq libos', 'samimiy nigoh'],
  },
  {
    id: 'cinderella',
    name: 'Cinderella',
    group: 'cartoon',
    imageNumber: 19,
    beautyScore: 88,
    popularityScore: 89,
    characterTypes: ['sabrli', 'optimist', 'orzuparast'],
    strengths: ['umid ramzi', 'dunyo boylab mashhur ertak', 'klassik brend kuchi'],
    charms: ['shaffof nafislik', 'oyoq kiyim ramzi', 'muloyim qiyofa'],
  },
  {
    id: 'rapunzel',
    name: 'Rapunzel',
    group: 'cartoon',
    imageNumber: 20,
    beautyScore: 90,
    popularityScore: 90,
    characterTypes: ['quvnoq', 'ijodkor', 'qiziquvchan'],
    strengths: ['zamonaviy ertak qahramoni', 'keng fandom', 'hazilkash energiya'],
    charms: ['uzun oltin soch', 'yorqin kozlar', 'quvnoq tabassum'],
  },
  {
    id: 'elsa',
    name: 'Elsa',
    group: 'cartoon',
    imageNumber: 21,
    beautyScore: 90,
    popularityScore: 94,
    characterTypes: ['irodali', 'mustaqil', 'sokin'],
    strengths: ['Frozen fenomeni', 'kuchli anthem', 'global merchandising kuchi'],
    charms: ['muzdek nafislik', 'qirollik holati', 'dramatik aura'],
  },
  {
    id: 'jasmine',
    name: 'Jasmine',
    group: 'cartoon',
    imageNumber: 22,
    beautyScore: 90,
    popularityScore: 90,
    characterTypes: ['dadil', 'erkinfikr', 'ochiqkongil'],
    strengths: ['sharqona ertak ikonasi', 'oz ovoziga ega obraz', 'klassik tanilish'],
    charms: ['sharqona gozallik', 'ifodali qarash', 'yorqin uslub'],
  },
  {
    id: 'mulan',
    name: 'Mulan',
    group: 'cartoon',
    imageNumber: 23,
    beautyScore: 89,
    popularityScore: 88,
    characterTypes: ['jasur', 'fidoyi', 'strategik'],
    strengths: ['qahramonlik timsoli', 'kuchli hikoya', 'madaniy tasir'],
    charms: ['tabiiy gozallik', 'qatiy nigoh', 'sodda nafislik'],
  },
  {
    id: 'ariel',
    name: 'Ariel',
    group: 'cartoon',
    imageNumber: 24,
    beautyScore: 89,
    popularityScore: 89,
    characterTypes: ['qiziqchan', 'orzuparast', 'quvnoq'],
    strengths: ['dengiz malikasi brendi', 'musical mashhurlik', 'yoshlar orasida tanilish'],
    charms: ['qizil soch', 'jonli kozlar', 'energetik tabassum'],
  },
  {
    id: 'moana',
    name: 'Moana',
    group: 'cartoon',
    imageNumber: 25,
    beautyScore: 90,
    popularityScore: 91,
    characterTypes: ['lider', 'jasur', 'samimiy'],
    strengths: ['yangi avlod qahramoni', 'kuchli syujet', 'motivatsion obraz'],
    charms: ['tabiiy tabassum', 'quvvatli aura', 'ochiq xarizma'],
  },
  {
    id: 'ezoza',
    name: "E'zoza",
    group: 'special',
    imageNumber: 26,
    beautyScore: 100,
    popularityScore: 100,
    characterTypes: ['mehribon', 'aqlli', 'jozibador'],
    strengths: ['yurakka yaqinligi', 'samimiy qollab-quvvatlashi', 'har vaziyatda ilhom berishi'],
    charms: ['tabassumidagi iliqlik', 'nigohidagi ishonch', 'qalbni tortuvchi nafislik'],
    isEzoza: true,
  },
];

const battlePower = (c: BattleContestant): number => c.beautyScore * 0.62 + c.popularityScore * 0.38;

// Low -> high power so rounds gradually become harder.
export const BATTLE_LADDER_IDS: string[] = BATTLE_CONTESTANTS
  .filter((c) => !c.isEzoza)
  .slice()
  .sort((a, b) => battlePower(a) - battlePower(b))
  .map((c) => c.id);

export const FINAL_FORCE_MESSAGES: string[] = [
  "VAR tekshiruviga kora bu raund qayta oynaladi.",
  "Hakamlar hayati yakdil: E'zoza finalda bolishi shart.",
  "Gozallik indeksi yangilandi, taqqoslash davom etadi.",
  "Bu tanlov qabul qilinmadi, final mezonlari kuchaytirildi.",
  "Tomoshabinlar ovozi: E'zoza hali tanlanmadi.",
  "Sistemada maxsus qoida ishga tushdi: E'zoza golib bolishi kerak.",
];

export const FINAL_FORCE_REASONS: string[] = [
  'Raqib kuchli, lekin yurak reytingi past.',
  "Mashhurlik bor, ammo samimiyat korsatkichi yetmadi.",
  "Kadr zor, lekin final aurasi E'zoza tomonda.",
  "Duel dramatik, baribir ideal profil E'zozaga mos.",
  "Kozlar ovozi bir narsa deydi: yakuniy tanlov E'zoza.",
];
